-- Execute este script no SQL Editor do Supabase.
-- Ele cria login seguro com isolamento total por usuario (RLS).

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  timezone text default 'America/Sao_Paulo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kanban_columns (
  user_id uuid not null references auth.users (id) on delete cascade,
  id text not null,
  title text not null,
  position integer not null,
  created_at timestamptz not null default now(),
  primary key (user_id, id)
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  category text not null default 'Geral',
  priority text not null default 'Media',
  priority_color text not null default '#FEF3C7',
  priority_text_color text not null default '#D97706',
  days_left integer not null default 7,
  status text not null default 'In Review',
  status_color text not null default '#FFE4E6',
  status_text_color text not null default '#E11D48',
  attachments integer not null default 0,
  comments integer not null default 0,
  progress integer not null default 0,
  column_id text not null default 'col-1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Atualiza updated_at automaticamente
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tasks_updated_at on public.tasks;
create trigger trg_tasks_updated_at
before update on public.tasks
for each row
execute function public.set_updated_at();

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row
execute function public.set_updated_at();

-- Cria dados iniciais no cadastro
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, email)
  values (new.id, new.email)
  on conflict (user_id) do nothing;

  insert into public.user_settings (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.kanban_columns (user_id, id, title, position)
  values
    (new.id, 'col-1', 'A FAZER', 1),
    (new.id, 'col-2', 'EM PROGRESSO', 2),
    (new.id, 'col-3', 'REVISAO', 3),
    (new.id, 'col-4', 'CONCLUIDO', 4)
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.kanban_columns enable row level security;
alter table public.tasks enable row level security;

-- Profiles
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (auth.uid() = user_id);

-- Settings
create policy "settings_select_own"
on public.user_settings for select
to authenticated
using (auth.uid() = user_id);

create policy "settings_update_own"
on public.user_settings for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "settings_insert_own"
on public.user_settings for insert
to authenticated
with check (auth.uid() = user_id);

-- Kanban columns
create policy "columns_select_own"
on public.kanban_columns for select
to authenticated
using (auth.uid() = user_id);

create policy "columns_insert_own"
on public.kanban_columns for insert
to authenticated
with check (auth.uid() = user_id);

create policy "columns_update_own"
on public.kanban_columns for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "columns_delete_own"
on public.kanban_columns for delete
to authenticated
using (auth.uid() = user_id);

-- Tasks
create policy "tasks_select_own"
on public.tasks for select
to authenticated
using (auth.uid() = user_id);

create policy "tasks_insert_own"
on public.tasks for insert
to authenticated
with check (auth.uid() = user_id);

create policy "tasks_update_own"
on public.tasks for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "tasks_delete_own"
on public.tasks for delete
to authenticated
using (auth.uid() = user_id);
